# Default initial positions for my_robot's ros2_control fake system

initial_positions:
  wrist_rotation_joint: 0
  gripper_left_finger_joint: 0
  gripper_right_finger_joint: 0
  joint1: 0
  joint2: 0
  joint3: 0